apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-nq0l
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-yvyu-tenant/rhtap-demo-app/hacbs-test-project-nq0l@sha256:8aeba9a654f6ccd2e93aee96bcdd86e208d617ad8389cadd009629618ae21745
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
