apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-nq0l
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-nq0l
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-nq0l
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-nq0l
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-nq0l
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-yvyu-tenant/rhtap-demo-app/hacbs-test-project-nq0l@sha256:95e13470f640ecdcfed92b73ab8f13d4e5406ef04f300564a2e07a808487ee56
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
